### ISSUE TITLE
Stabilizer Trim calcs too low at MTOW

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#204]
https://www.youtube.com/watch?v=HcprGZnhgv8

**Comment by Marauder2882** [comment]
Did you load the plane via the FMC or via the XP menus?  The CG & TRIM logic is only valid if loaded via the FMC and the Gross Weight entered in the PERF INIT page.

**Comment by MCCVeen** [comment]
> Did you load the plane via the FMC or via the XP menus? The CG & TRIM logic is only valid if loaded via the FMC and the Gross Weight entered in the PERF INIT page.

Everything via the XP Menu, and checked that the fuel was correctly set up as that's a pain the butt with the xp menu. Correct values were in the FMC

**Comment by Marauder2882** [comment]
if you set everything up via the XP menus then that's the problem.  the PAX, CARGO and/or FREIGHT must be loaded via the FMC screens accessed from the GROUND HANDLING menu.  otherwise, the FMC calcs don't know where the datum points are for the weight since the XP menu sliders simply loads all passengers in a vertical plane above the default CG.  thus, the STAB TRIM calcs have no way of knowing where the true CG%MAC is unless you load via the FMC.
