### ISSUE TITLE
Baro Discrepancy Msg on Eicas

### ISSUE THREAD

**Issue by almarine91** [mSparks43/747-400#221]
Frequent and unnecessary popups of the warning on eicas.
Suggested to put a tollerancy of maybe 2/3 hPa

or (better)

an option (on by default) to synchronize CAPT and FO baro settings.

**Comment by MCCVeen** [comment]
The thing is that inhg and hpa are linked in the 744, so 1013.2 will be 29.92, 29.93 will be 1013.8. In the real thing it would just stay at 1013.0, 1014.0 but in the mod it adds a decimal so if you have set 1013, it may actually be 1013.8 or 1013.2 instead of 1013.0. It also explains why you have to scroll once to scroll a number further for inhg and multiple times for hpa.

**Comment by mSparks43** [comment]
They now by default synchronise with an option in the simconfig setting to disable automatic synchronisation
