### ISSUE TITLE
Flap bug numbers size

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#259]
The size of the numbers of the flap bugs on the speed tape are too big and the little lines left of em are missing.

![image](https://user-images.githubusercontent.com/75425109/103981064-52665000-5181-11eb-93a2-6d9c01e92f79.png)
![image](https://user-images.githubusercontent.com/75425109/103981073-598d5e00-5181-11eb-8972-09aa1fd91755.png)

**Comment by Matt726-S** [comment]
yeah, who touched my textures...
if someone doesn’t fix it before me i’ll fix it on friday

**Comment by mrshiljo** [comment]
I can change that...but...I need someone first to show me how to enlarge speed font, ned to be a little bigger, and then I can change and sharpen all font and adjust the size. But, I did this on my copy with flaps speed. I added a green pointer next to a number...It needs to be adjusted more to left on top of speed tape. So pointer should be visible on speed tape. I now have it pulled to right...because numbers are adjusted to be in the space between tape and horizon...


<img width="1280" alt="Desktop Screenshot 2021 01 23 - 05 48 45 36" src="https://user-images.githubusercontent.com/76166015/105569066-cb97a280-5d3e-11eb-8548-6237e031f5f1.png">

So the white numbers on tape, scrollingones should be also bigger, but i dont know which one they are. Can someone point me soi adjust them
