### ISSUE TITLE
Slats do not retract when thrust reversers out.

### ISSUE THREAD

**Issue by jmsantafe** [mSparks43/747-400#36]
When the thrust reversers are out, the middle and inboard sets of slats are supposed to retract. https://www.youtube.com/watch?v=xGmV5q3An8s
They come back out when the spoilers are retracted.

**Comment by jmsantafe** [comment]
https://www.airliners.net/forum/viewtopic.php?t=751501

**Comment by mSparks43** [comment]
looking for if this is actually on the thrust reversers or actually wheels on ground + spoilers fully up
found a few more videos
https://www.youtube.com/watch?v=MVb6x8eYCO8
https://www.youtube.com/watch?v=N1YHrBBG9Hg
https://www.youtube.com/watch?v=TNwZ7-w7oBE
https://www.youtube.com/watch?v=XsBABDqg-AI

They're all using thrust reversers and spoilers.
Can't find anything about this in the documentation I have (in fact didn't find slat/slats or "kruge" at all so maybe they are called something else)
I've just this on all three wheels spoilers activated + thrust reverse active, mostly because in
https://www.youtube.com/watch?v=TNwZ7-w7oBE

It doesn't look like they start retracting until after thrust reverse is active, even though the spoilers are up and the wheels are on the ground.
This should have a positive impact on landing performance, reducing lift and giving better ground contact after touchdown.

Video of the fix
https://www.youtube.com/watch?v=2Gf8y7wmV8Y
