### ISSUE TITLE
Random bugs

### ISSUE THREAD

**Issue by Athos4** [mSparks43/747-400#387]
When I fly the B744, I get to have random bugs but here the more reccurent:
- Engine not starting (even with the procedure followed)
- No hydraulic pressure on one pump (n°1 most of the time)
- Generator failure (n°2 most of the time)
- and other bugs which are already been reported

**Comment by Matt726-S** [comment]
1 please send a photo of the overhead panel since everyone else can start the engines, it’s probably a wrong procedure done on your part
2 my understanding of the 747 hydraulic system is not that great, but i believe that if you push the engine hydraulic pumps on (buttons below the knobs), the hydraulics will try to gain pressure from the engine pumps. however, the engine pumps do not have power on the ground, so try pushing the button off. if you have it on, its still normal for the number 1 hydraulic to not gain power immediately. if you want hydraulic pump 1 to have pressure, try turning the demand pump knob to auto/on or switch it to the auxiliary pump (not available in the msparks model), not sure about the demand pump to auto/on without the engine button switch on, but just try it

**Comment by mSparks43** [comment]
Hydraulic system has followed 
https://www.youtube.com/watch?v=HrRQAtBEJBQ

Since release one
I can't recreate the other issues even on that (although a couple sound like original XP 744 issues - are you sure you are choosing the correct plane when you start a flight?).
