### ISSUE TITLE
Unreadable Cockpit Textures

### ISSUE THREAD

**Issue by crazytimtimtim** [mSparks43/747-400#401]
Some textures in the cockpit have very low resolution and are unreadable.
Clock 
![image](https://user-images.githubusercontent.com/64425497/108651146-c5ecc400-7486-11eb-8348-fc6de1f8a547.png)
Aft Overhead Panel (Nothing on this panel is modeled yet, so I guess for now it doesn't really matter.
![image](https://user-images.githubusercontent.com/64425497/108651229-f16fae80-7486-11eb-8f34-c4a37b0a41eb.png)
There are a few others, such as the third oxygen mask, cockpit door, and smoke evacuation handle, but those are less important.

**Comment by Matt726-S** [comment]
a bit of a solution could be to download notchmasters textures. they are a bit higher resolution and the pbr is great. the aft overhead textures don’t matter because no one uses them.

**Comment by crazytimtimtim** [comment]
> 
> 
> a bit of a solution could be to download notchmasters textures. they are a bit higher resolution and the pbr is great. the aft overhead textures don’t matter because no one uses them.

Do you mean to download the Notchmaster 747 and just copy the cockpit textures into the sparky?

**Comment by Matt726-S** [comment]
yes

**Comment by mSparks43** [comment]
Only way this can be improved is to up textures like Cockpit_Panel to 4k, but doing so will likely make the plane useless for anyone with less than 8GB VRAM.

Its also "per livery", so closing these as a wont fix

**Comment by crazytimtimtim** [comment]
> Only way this can be improved is to up textures like Cockpit_Panel to 4k, but doing so will likely make the plane useless for anyone with less than 8GB VRAM.
> 
> Its also "per livery", so closing these as a wont fix

Shouldn't it be fine just for the cockpit texture? The entire aircraft doesn't need 4k, just cockpit_panel. For release, we can have two download options. One 4k and the other lower.

**Comment by mSparks43** [comment]
It "might" be OK, someone with a low end graphics card would need to test, but since its already per livery:
https://github.com/mSparks43/747-400/blob/master/liveries/747-400%20Global%20Supertanker%20by%20Fscabral/objects/747_cockpit/Cockpit_Panel.dds
https://github.com/mSparks43/747-400/blob/master/liveries/Boeing%20House%20-%20N401PW/objects/747_cockpit/Cockpit_Panel.dds
https://github.com/mSparks43/747-400/blob/master/liveries/British%20Airways/objects/747_cockpit/Cockpit_Panel.dds
https://github.com/mSparks43/747-400/blob/master/liveries/Metal/Objects/747_cockpit/Cockpit_Panel.dds
https://github.com/mSparks43/747-400/blob/master/liveries/Northwest%20N663US/objects/747_cockpit/Cockpit_Panel.dds

+ their lit and normal textures

Thats a fairly big texture rework for something that might destroy the plane for more than half the people that fly it.
Of course, welcome to rework them, or build it into the paint kit, but its a lot more than "just" changing the text using the correct font.
4k textures consume about 400MB of VRAM, so this and the oxygen writing would need ~1GB of VRAM _just_ for those two textures.
