### ISSUE TITLE
autopilot disconnect works only after 2nd disconnect

### ISSUE THREAD

**Issue by Juppie902** [mSparks43/747-400#432]
from 0:28
https://www.youtube.com/watch?v=qQBylYr6tdE&feature=youtu.be

**Comment by oMrSmith** [comment]
I noticed this as well and regard this as one of the most important issues... However in your
video the disconnect actually works and instead engaging CMD does not work
with the FMA remaining "FD" eventhough the CMD MCP light shining...

**Comment by mSparks43** [comment]
Please retest

**Comment by oMrSmith** [comment]
Did a quick test.
Result: Disco Bar seems to work now on first hit.

2 Problems that remain:
1. The shortcut command for the Disco button (on the yoke) still doesn't work.
2. Disengaging CMD also erases all AP modes.

Example:
You Fly on 
CMD
SPD | LOC | GS, 
then disconnect CMD in order to hand-fly
and end up with nothing
FD
      |         |
