### ISSUE TITLE
FD synced

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#484]
when you turn on FD on one side, it turns it on for both. the switch also has to be off for both sides for it to turn off on the PFD which is unrealistic. each switch on each side should only control that side’s PFD

**Comment by mSparks43** [comment]
As far as I can see, the FD switches only enable/disable the bars (not the FMA/ADFS) which is how its currently configured.
What are you referring to? and do you have an fcom reference.

N.B. issues without an fcom/documentation reference will be closed soon.

**Comment by oMrSmith** [comment]
I think he means, that 
the left FD switch should only toggle the
FDs of the left PFD and
the reight FD switch should only toglle the
FDs of the right PFD.

**Comment by mSparks43** [comment]
yes, but take this one from the REF issue, is the FD switch on or off
![image](https://user-images.githubusercontent.com/6773686/115133180-82d24b80-a006-11eb-9178-b099f4558900.png)

I assume off -> because no FD bars. (with the other on providing the FMA)
the two switches do control their respective FD bars, with either one on required for FMA.
