### ISSUE TITLE
AP: Issues after Take off with TOGA without VNAV armed

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#507]
All of the following issues apply 
after take off with TOGA 
_without_ VNAV armed:

- [ ] Thrust mode "HOLD" should be followed by "THR REF".
- [ ] Bug: TOGA pitch FD is not showing pitch for MCP Speed.
- [ ] Bug: Switching over to VNAV **_after_** reaching the CRZ ALT with FLC, 
will result in the false thrust mode "THR REF", causing overspeed.
- [ ] Bug: Opening the SPD Window during VNAV PTH has then no longer any effect.

I believe the thrust mode THR REF should simply _never_ occur together with VNAV PTH.
It is basically a thrust mode to provide climb power.

All issues are captured on the following short video:
https://youtu.be/LiFDneV7K-s

**Comment by mSparks43** [comment]
For 1 and 2
The only thing I can see different from
https://www.youtube.com/watch?v=sDa1ukA3CUo&t=990s

Is it should say "HOLD" instead of be blank until you hit flch after a non VNAV take off

The other two are very specific to the flight in the video, the reason for the THR REF when you hit VNAV is its accelerating to cruise speed, I suspect after that is something like you are past/pass ToD during the acceleration and it doesn't switch correctly into SPD while in THR REF and passing the ToD.

**Comment by oMrSmith** [comment]
"the reason for the THR REF when you hit VNAV is its accelerating to cruise speed"
I could have accelerated manually first. It would still change to THR REF during VNAV PTH which it should never do as I believe.

**Comment by oMrSmith** [comment]
Also: I believe that the thrust mode HOLD should be followed by the thrust mode THR REF.
HOLD is only engaging during take off so you can add more thrust or reject the take off.

**Comment by oMrSmith** [comment]
Sounds good I'll test soon.

**Comment by oMrSmith** [comment]
Muharhar! Now it works. Man, you did it again! Thx!
It's getting better and bettter.
