### ISSUE TITLE
AP: Issue with the LOC button

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#514]
- [ ] Bug: When using the **LOC Button** for the very first time, 
you have to click it _two or three times_ 
in order to "wake" it up 
and arm or engage the localizer.

**Comment by mSparks43** [comment]
![image](https://user-images.githubusercontent.com/6773686/117186099-cd134500-adda-11eb-80c6-74a9c9fc0e26.png)

**Comment by oMrSmith** [comment]
The LOC button does the right thing,
it's just that you have to click it several times
to trigger its function!

**Comment by mSparks43** [comment]
> The LOC button does the right thing(!),

There's a reasonable chunk of logic to change, currently capturing the LOC in APP is limited to 5 degrees
https://github.com/mSparks43/747-400/blob/27120432c64bcafec7583214864747484b2449a5/plugins/xtlua/scripts/B747.70.xt.autopilot/B747.70.xt.autopilot.lua#L1915

it went that low because if it was much more than that on the old LNAV mode it would oscillate all over the place once it captured it.

currently the LOC button is all the old logic, basically from the original systems, 
APP works by setting a flag then the monitor gets it there, this "fake" arming is the reason for that FMA showing LOC as captured and armed bug.

APP still needs some work, and LOC needs making work the same way. probably ready tomorrow.

**Comment by oMrSmith** [comment]
Wow: 5 degrees! That explains a lot, I guess.
Thanks for all the effort you put into this!

**Comment by mSparks43** [comment]
> I suppose, fixing this issue will _vastly improve the safety of the ILS approach_: Currently the late capturing of the LOC
> also delays capturing the GS as a consequence
> since the GS cannot capture before the LOC as I believe...

The main issue with letting xplane capture the LOC sooner is the xplane LOC autopilot is .... not great. in fact a complete mare turning in onto the course and snaking all over - often if its a tight turn going inside and outside of the LOC envelope and losing reception.
testing a bit today, its going to take a bit longer to get the logic right + flight tested

**Comment by oMrSmith** [comment]
Take your time! Looking forward to test it.

**Comment by oMrSmith** [comment]
Just did a quick test, arming worked very well!

Somehow the legs went missing, but I'll recheck installation...
![747-400 - 2021-05-08 09 56 54](https://user-images.githubusercontent.com/78870770/117531673-f6eb8800-afe3-11eb-9f59-6e901d549385.png)

**Comment by oMrSmith** [comment]
fixed

**Comment by oMrSmith** [comment]
Man, I think you got this right! Congrats and thanks so much for improving this!
