### ISSUE TITLE
AP: Issue when switching from FLC to VNAV during descend

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#516]
**During descend after passing the T/D:**

- [x] Bug: VNAV will get stuck in **VNAV SPD**
when switching from **VNAV PTH** to **FLC** and back.

https://youtu.be/ThCLutHaj5k

**Comment by oMrSmith** [comment]
I'll restest.

**Comment by oMrSmith** [comment]
Retest: This issue is still triggering.

**Comment by mSparks43** [comment]
OK, I watched the video again, I see why its misbehaving
![image](https://user-images.githubusercontent.com/6773686/116890114-90eeb180-ac2d-11eb-89df-892af1a7c0b3.png)
VNAV is confused, because the descent path is several miles in front, and altitude is well below cruise altitude when VNAV is reactivated. 
I think in this case it should continue at the same altitude until it re intercepts the descent path.
I'll need to flight test this more to make sure its handling the conflict properly.

Part of this it I'm not 100% sure _exactly_ what it should do in the situation where VNAV is engaged less than 50nm from ToD and the descent path is significantly above the current altitude.

E.g., 
I could mark "descent started" and persist it even when VNAV is disengaged, then if VNAV is later engaged below the path it holds altitude (rather than trying to climb up to the path) until it intercepts it.

But I should probably review the training materials before spending time on that.

**Comment by oMrSmith** [comment]
"I think in this case it should continue at the same altitude until it re intercepts the descent path."
This sounds pretty reasonable to me. It's strange though, that it engages VNAV SPD instead of VNAV PTH, isn't it?
is there any other occasion that VNAV would engage VNAV SPD during descend?

**Comment by oMrSmith** [comment]
Even if you would switch over to FLC only for 3 seconds, it will trigger VNAV SPD
when switching back.

**Comment by mSparks43** [comment]
> It's strange though, that it engages VNAV SPD instead of VNAV PTH, isn't it?

Currently, since you are before ToD, and lower than cruise, it assumes you were climbing to cruise when VNAV is engaged, FLCH and VNAV SPD share most of the same state, target altitude doesn't get updated because you are closer than 50nm from TOD.

If you were to dial in a nearer altitude on the MCP it would finish the FLCH to that, then go to VNAV ALT

https://www.youtube.com/watch?v=sDa1ukA3CUo&t=1650s

**Comment by oMrSmith** [comment]
"Currently, since you are before ToD, and lower than cruise, it assumes you were climbing to cruise"

Maybe we need a Top of Climb :D .

**Comment by mSparks43** [comment]
> _after_ you have passed the (initial) T/D.

true, but, ToD is a calculation of altitude and distance for an ~idle descent to the EOD, because you descended so much below the descent path _before_ engaging VNAV again there's several options to choose from.

 - climb up to the path. (definitely dont think its this)
 - hold current altitude until intercepting the path.
 - descend, but at a reduced rate of descent to intercept the path (think the real one does this from what I've seen in the docs).

What its doing now is exactly what you tell it, flch to an altitude and then resume VNAV.

**Comment by oMrSmith** [comment]
"What its doing now is exactly what you tell it, flch to an altitude and resume VNAV upon intercepting the path."
Yeah. My assumption was just, that it should do this in VNAV PTH instead of VNAV SPD...

"you descended so much below the descent path" I did not notice this during the test-flight because it doesn't make sense.
I was descending with VNAV. Then at 10.000 ft I _leveled off_ until I decelalerated down to 250 knots.
When I reengaged VNAV all of a sudden VNAV thinks I'm low on profile. Whenever you disengage VNATH PTH and reengage it
the descend path is recalculated putting the T/D further away than it was before.

**Comment by oMrSmith** [comment]
Could it be that the idle descend path is based on a speed which is higher than 250 knots?

**Comment by mSparks43** [comment]
flch descends much faster than an idle descent. an idle descent is targeting the next destination speed/location/altitude, flch just descends as quickly as possible while maintaining the speed on the bug. 

so in vnav descent the path is a constantly reducing speed from cruise speed to restriction speed for when it reaches the next waypoint.
so when you flch down, you fall well below the descent glideslope, but are also now faster than you would have been if you hadn't flch'd down, net result is this pushes the idle descent path further away than it was before.

I think the solution is to store that a descent was started in the flight (crossed a tod, or started a descent 50nm from it), then have vnav resume in descent mode once reactivated.

> FLC did not cause the plane to descend!

initially, however, once you reengaged vnav it was vnav speeding down towards 2000 feet, because you engaged vnav before current tod, below cruise altitude (identical conditions to engaging vnav after take off)

**Comment by oMrSmith** [comment]
"I think the solution is to store that a descent was started in the flight (crossed a tod, or started a descent 50nm from it), then have vnav resume in descent mode once reactivated."
I think this sounds right!

To FLC:
The descend rate is very dependend on the selected SPD. If you select a SPD which is much lower than the current
IAS, the plane will pitch up to slow down which will cause a level off until the IAS has decelerated to the selected SPD,
afterwards it will descend faster than an idle descend, like you said.

**Comment by oMrSmith** [comment]
I did another test. It is like you said:
If I switch back from FLC to VNAV with the T/D = 0 nm, it will engage VNAV PTH as expected.
If I switch back from FLC to VNAV with the T/D > 0 nm, it will engage VNAV SPD.

**Comment by mSparks43** [comment]
obviously starting a line with # doesnt put it in the commit message
https://github.com/mSparks43/747-400/commit/27120432c64bcafec7583214864747484b2449a5

**Comment by oMrSmith** [comment]
I can now switch back from FLC to VNAV PTH even when low on profile! Thanks man!

I noticed one issue during the descend below 10.000 ft. 
It's probably not related to this issue/fix:
VNAV PTH tends to do a lot of _pitching for speed_,
(befor FAF) which lead me quite high on profile.
But I'll have to test more...

**Comment by oMrSmith** [comment]
... Maybe it was this 180/5000. It cannot be deleted can it?
