### ISSUE TITLE
AP: Briefly Engages with FD Off

### ISSUE THREAD

**Issue by crazytimtimtim** [mSparks43/747-400#540]
WHen engaging the A/P with Flight DIrectors off, it briefly engages for a fraction of a second, then disengages.

**Comment by crazytimtimtim** [comment]
what...?

I know it should not engage. The problem is that it briefly engages, then disengages. It shouldn't engage at all.

**Comment by mSparks43** [comment]
maybe - the logic is a little weirder than that, because the autopilot and automatic flight directors are different systems, so what happens now is the autopilot powers up, which lights the light, then the ap finds no flight directors and powers down.
an alternate option would be it could fires the ap disconnect. but since I havent found a description in the fcom either way for what happens if you try and engage the autopilot system without the flight director system right right now it simulates what is described (which is connected to needing to cycle the fd switches off/on to fully clear the ap after a disconnect is pressed)

**Comment by mSparks43** [comment]
looks like this fixed itself at some point
