### ISSUE TITLE
FMC: Confusing Issue on the PROG page

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#547]
- [ ] Bug: At some point the DIST to the DEST 
is _shorter_ than
the distance to the waypoint _before_ the destination runway.

![image](https://user-images.githubusercontent.com/78870770/118393387-25e6a700-b63f-11eb-9c46-ae994a7a3896.png)

According to the LEGs page LXGB should be 5nm further away than GB27F...

https://youtu.be/SwK09XdCZAQ?t=571

**Comment by mSparks43** [comment]
yeah, so not _sure_ exactly how to deal with this, it basically comes from not adding the approach distance (or go around) onto the end of the plan, so its finishing at the 3nm of the next waypoint.
but its not enough to just add the distance from the next waypoint to the airport, because they could be in the same place with another 15 miles of approach pattern remaining, or the next could be a missed approach waypoint - and there's no easy way to tell which is which.

**Comment by oMrSmith** [comment]
I see and hope you'll find some genious trick to solve this ;)

**Comment by oMrSmith** [comment]
Maybe the target altitudes of the waypoints can help to determine which one is "the last"

**Comment by oMrSmith** [comment]
Hey @mSparks43 I think the issue is still present:
![747-400 - 2021-08-23 01 37 56](https://user-images.githubusercontent.com/78870770/130373880-77cf8c8b-db2c-40ea-acc4-cb78e7d9041e.png)

**Comment by mSparks43** [comment]
> Hey @mSparks43 I think the issue is still present:
> 
> ![747-400 - 2021-08-23 01 37 56](https://user-images.githubusercontent.com/78870770/130373880-77cf8c8b-db2c-40ea-acc4-cb78e7d9041e.png)

Hmm, not sure where you where, but that looks like you are 2 miles from landing and 10nm of go around programmed if you dont.

**Comment by oMrSmith** [comment]
Shouldn't the DIST to the DEST on the progress page
equal the distance to the RW
and not include the go around?

**Comment by mSparks43** [comment]
> equal the distance to the RW
> and not include the go around?

I'm not sure when it should switch over, but then you'd be back to where you were before, with GBM03 further away than the airport.
