### ISSUE TITLE
AP: Issue with HDG SEL

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#574]
- [ ] Bug: When switching from LNAV to HDG SEL for the very first time,
CMD will disconnect an cause further bugs:
- [ ] Bug: Re-engaging CMD will mess up the AP and kill both roll and pitch mode.
- [ ] Bug: Switching from VS to VNAV will engage VNAV PTH instead of VNAV SPD.
- [ ] Bug: VNAV SPD can't be reengaged unless preselecting FLC CHG.

https://youtu.be/NtwfqmyFOsk

Sorry for sound issue...

**Comment by oMrSmith** [comment]
Might be the same with HDG HLD, haven't tried yet.

**Comment by oMrSmith** [comment]
Hi @mSparks43 do you think you could add this issue to the second release?
This bug is quite striking and I think it is rather new...

**Comment by mSparks43** [comment]
I need a full procedure video for this - pretty much from start up, can't recreate it, and can't see anything that would cause an AP disconnect other than XP failing the AP.

**Comment by oMrSmith** [comment]
Alright I'll make one today...

**Comment by oMrSmith** [comment]
Here it comes:
https://youtu.be/exgpJTZISn8

**Comment by mSparks43** [comment]
> Here it comes:
> https://youtu.be/exgpJTZISn8

So, still not doing the same for me copying exactly what you did
![image](https://user-images.githubusercontent.com/6773686/123554598-020b9a80-d781-11eb-8242-090425bfce1e.png)
could you make sure its on the latest systems build, 06/27 18:32 at time of writing, FMC ident page
![image](https://user-images.githubusercontent.com/6773686/123554626-27000d80-d781-11eb-84fe-39395115e744.png)

if its still doing it, grab the text content from the console window as you hit heading select, it looks to me like the disconnect is being caused by the reset in "reset AP in B747_ap_afds", which fires when it detects XP has disconnected the AP servos, but I have no idea why its being failed, there might be some hint in that systems log.

**Comment by oMrSmith** [comment]
Pre command laminar/B747/autopilot/button_switch/heading_select
post command laminar/B747/autopilot/button_switch/heading_select
Pre command laminar/B747/autopilot/button_switch/heading_select
post command laminar/B747/autopilot/button_switch/heading_select
Command once sim/autopilot/gpss
Command once sim/autopilot/heading
Pre command laminar/B747/autopilot/button_switch/heading_select
post command laminar/B747/autopilot/button_switch/heading_select
Do Command once sim/autopilot/gpss 0000000000000576
Do Command once sim/autopilot/heading 0000000000000563
Pre command laminar/B747/autopilot/button_switch/heading_select
post command laminar/B747/autopilot/button_switch/heading_select
Pre command laminar/B747/autopilot/button_switch/heading_select
post command laminar/B747/autopilot/button_switch/heading_select
reset AP in B747_ap_afds
full reset AP in B747_ap_afds
Command once laminar/B747/autopilot/mode_reset
Do Command once laminar/B747/autopilot/mode_reset 0000000000000CAD
Pre command laminar/B747/autopilot/mode_reset
post command laminar/B747/autopilot/mode_reset
B747_ap_reset_CMDhandler
B747_ap_all_cmd_modes_off
main command laminar/B747/button_switch/warn_caut_capt
main command laminar/B747/button_switch/warn_caut_capt
main command laminar/B747/button_switch/warn_caut_capt
main command laminar/B747/button_switch/warn_caut_capt

**Comment by oMrSmith** [comment]
(Happened again on the latest build...)

**Comment by mSparks43** [comment]
>Pre command laminar/B747/autopilot/button_switch/heading_select
>post command laminar/B747/autopilot/button_switch/heading_select
>Command once sim/autopilot/gpss
>Command once sim/autopilot/heading

All good to here

>reset AP in B747_ap_afds
XP has turned off the autopilot....

___
I even just tried it with a key bound to heading select (and also the look based versions for my cockpit dials) and not seeing anything similar.
How are you switching the AP on?

>AP heading up
Suppose it could be, the XP heading up/down, and the 744 heading up down are different commands, could you try it with mouse clicking the buttons rather than any key bindings - it could be a key binding to the wrong but similar command.

**Comment by oMrSmith** [comment]
So X-Plane is disconnecting my AP when I click on HDG SEL :D
That's certainly strange. But at least is seems like
it's only my problem.
It's not the shortcut for heading up. I just tried...

**Comment by oMrSmith** [comment]
Issue seems to be gone now.
I changed some short cuts - for example the one for trimming...
May this on was triggering the disco.
