### ISSUE TITLE
[AP] Bug when trying to reengage VNAV

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#713]
When trying to switch back 
from FLCH to VNAV during descend,
VNAV gets armed but not engaged:

https://youtu.be/7dJqL-puDlo?t=5820

These are the things that need fixing first, I'm sure!
People try out this wonderful plane, then they put
it aside because of these little AP glitches.

I know, many of them have already been adresses!

PS: I would have known how to deal with it.
Cause you can switch from VS to VANV without a problem,
but it doesn't work sometime when going from FLC to VNAV.

**Comment by mSparks43** [comment]
FLCH'ing during descent will put you well below the glideslope (and possibly below altitude restictions), VNAV needs to know how to resolve that and will [should] switch to armed when activated from either ALT HOLD (hold current altitude until the glideslope is intercepted, probably what he wanted) or VSPD (return to the glideslope). 
It didn't engage because it is inhibited from initiating a climb on its own during the descent phase.
See also:
https://www.smartcockpit.com/docs/Cognitive_Engineering_Analysis_Of_VNAV.pdf

**Comment by oMrSmith** [comment]
It's hard for me to imagine, that this behavior is correct.
Obviously VNAV s_hould not descend_ if you have descendend below the GP using FLCH, 
but(!): IF the mode gets only armed, you don't have any active pitch mode...

**Comment by mSparks43** [comment]
>At least I have never seen VNAV arm in the air in a 737...

I'm not saying its right or wrong, the issue is, as per that document

>The perceived complexity of the VNAV function has resulted in airline operators training
only the basic features to operate the VNAV function (Hutchins, 1994; Lenorvitz, 1992).
The airlines are effectively relying on the pilot community to discover and informally
communicate to each other ways of using the function in all fligh regimes

In that video VNAV is disarmed, the plane is taken well below what VNAV calculates for, then VNAV is rearmed but is not in a situation it can activate, it doesn't make the choice between holding the current altitude below the altitude restriction or climbing to the altitude restriction during descent.

Neither choice is right or optimum, so the question is what would be the fix? force a climb in descent or risk a crash into a mountain?

**Comment by oMrSmith** [comment]
Did you know, you can fool the system?
If VNAV gets armed but not engaged,
you can switch to VS then back to VNAV
and VNAV PTH will engage.

**Comment by oMrSmith** [comment]
Besides that:
Doesn't the PFD even show your on profile
and still not engage VNAV PTH?

![image](https://user-images.githubusercontent.com/78870770/140077561-b8944588-601a-4593-99bf-5fb9ebc68d36.png)

**Comment by crazytimtimtim** [comment]
> Neither choice is right or optimum, so the question is what would be the fix? force a climb in descent or risk a crash into a mountain?

What? It's not supposed to climb during descent, but it should level off until it intercepts the path again.

**Comment by mSparks43** [comment]
> Did you know, you can fool the system?

Yes, atm, in descent
if you are in ALT HOLD before arming VNAV, it will intercept the glideslope from the current altitude.
If you are in VS before arming VNAV it will (should) climb up to or descend down to the glideslope.
If you have no active pitch mode before arming VNAV its up to the pilot to intercept the glideslope.

**Comment by oMrSmith** [comment]
I just did the following test in the ZIBO:
Descended 1000 ft below GP using FLC
then switch to VNAV
![image](https://user-images.githubusercontent.com/78870770/140084801-0210da72-3460-4a94-b214-b76c03b251dd.png)

One thing is for sure,
VNAV engages immediately without arming,
interestingly enough its VNAV SPD.

**Comment by crazytimtimtim** [comment]
He's right. VNAV is only armed on the ground. If you press it in the air it just immediately engages.

**Comment by mSparks43** [comment]
> Interestingly enough its VNAV SPD. Probably because I'm way too fast

VNAV SPD is a FLCH equivelent, but afaik in the 744 its only used for climbing. So this doesn't answer the question of what it should do.



> VNAV is only armed on the ground.

Pressing any AP button "arms" it first, it then activates when its in a state it knows how it should fly the plane, trouble here is the way it should fly the plane isn't defined, and we don't have what it _should_ be.

**Comment by oMrSmith** [comment]
I would propose to take the best work around.
This could be to hold the current ALT with the THR mode simply going to SPD.

Better a solid and predictable AP with some aspects not 100% realistic,
than an unsolid and unpredictable AP with some aspects not 100% realistic.

What do you think?

**Comment by oMrSmith** [comment]
Holding the ALT could be programmed like VS = 0.
This way it could be easily changed later to something like - 500 fpm...

**Comment by mSparks43** [comment]
> I would propose to take the best work around.

yeah, picking one is problably best.
I'd suggest auto firing alt hold in this situation, that will/should recalculate a new ToD sometime in the future, and hold current altitude and speed until it gets there.
