### ISSUE TITLE
AP: LOC gets lost

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#714]
LOC got lost for no good reason:
https://youtu.be/7dJqL-puDlo?t=6255

Also:
LAND 3 should not engage until both LOC
and GS are captured, shoult it?

**Comment by mSparks43** [comment]
~Reasonably sure this is XP loosing the localiser because its to far below the glideslope as it hits final

> LAND 3 should not engage until both LOC
> and GS are captured, shoult it?

definitely shouldn't, and then some:

1500 FT RADIO
At 1500 ft R, the remaining two autopilot channels engage. LAND 3 will be
annunciated in green, FLARE and ROLLOUT in white on the PFD shortly after.

**Comment by oMrSmith** [comment]
> Reasonably sure this is XP loosing the localiser because its to far below the glideslope as it hits final

Ah, so the LOC does not work indipenently from the GS (in X-Plane)?
Shouldn't it be technically possible to fly LOC and VS,
some approaches are LOC only approaches anyway...

**Comment by mSparks43** [comment]
> Ah, so the LOC does not work indipenently from the GS (in X-Plane)?
Not so much the aircraft systems (can do LOC or LOC/GS), and more the transmitter
![image](https://user-images.githubusercontent.com/6773686/143933013-880d9c6a-371f-4af5-9b89-d27167e0da2e.png)
If you are to low/high or too far left/right it can't capture them.
