### ISSUE TITLE
During descend after a few seconds the throttle moves from idle and start accelerating, instead of trying to keep descend speed

### ISSUE THREAD

**Issue by abuelo007X** [mSparks43/747-400#744]
**Describe the bug**

When descend starts throttle moves as expected to IDLE and the PFD shows that, but after a few seconds moves back to speed SPD starting to accelerate a little bit, then back to IDLE, but inmediatly moves the thorttle to the position I have on my physical throttle, and show HOLD on the PFD. Then moving my throttle back to IDLE everything starts to work as expected.

I kept my thorttle in physical throttle in IDLE for rest of the descend and landng (in this case it was an Autoland), and the A/T worked as expected no taking into consideration my throttle position.

Something similar si happening during Takeoff while pressing TOGA button, and the A/T fights versus the physical throttle position (for this one, I have not attached a video, but may open another issue as soon as I have it)

# Please provide documentation references:

Place an x to check the boxes:
- [x] Something found during a flight test
- [x] No FCOM reference included as this is related to behaviour on the sim, rather than an opperational procedure
- [x] checked [current](https://github.com/mSparks43/747-400/blob/master/plugins/xtlua/scripts/B747.68.xt.fms/activepages/version.lua) FMC revision ident (downloaded version from today latest commit)
- [x] Video included (where applicable)
- [ ] Screenshot included (where applicable)

### Bug reports:

It seems there is some issues related to the physical throttle status versus the expected behaviour with the Auto Throttle activated. that is my preliminary conclusion

https://user-images.githubusercontent.com/88299309/147870921-86c6215d-ee3a-4294-a1ad-55bbc8175cfb.mp4

**Comment by mSparks43** [comment]
I can tell you what happened, not so sure what the fix is.

You had a descent speed set of 270/0.805, prior to starting descent your target speed was 267kts, as you started accelerating due to the descent it switched to a 0.805 target and added a little bit of gas before converting to hold (throttles back to you)

My first thought it is probably enough to make it just repeat fire -> to idle during descent if accelerating.
But it actually it does at the end of the video

might be it needs "switch to mach descent" inhibiting if the target in kts is < 270, might be a mach descent is normal.....

**Comment by abuelo007X** [comment]
At the end of the video who moved to idle was me as I mentioned above :-)
It never happened automatically. I moved manually my throttle to idle in order to avoid the continue increase in speed

That was the reason I communicated this issue. it it was doing it automatically, as you mention, then probably was a minor concern, but that was not the case.

**Comment by abuelo007X** [comment]
It worked perfectly well !!!! Thank you for finding a solution that quickly and for this amazing work 👍 

Just noted some behaviour with N1 during descend that I guess is incorrect, and it can also be seen on the video above.
When descending N1 in IDLE shows values  above 40 (in the video above around 50), in my current test between 42-45.
Let me know if need to open a case and upload the video with this findings

**Comment by mSparks43** [comment]
> Let me know if need to open a case and upload the video with this findings

No need to be shy opening issues, cant guarantee they'll get fixed quickly, I actually noted this one literally 12 months ago when I did the fmc drag required fmc message and left this note for myself:
![Screenshot_20220104-050850_Chrome](https://user-images.githubusercontent.com/6773686/148008601-81c41869-0dc2-4b49-b099-6744942ee3a3.jpg)

fix was then just "it knows its going too fast here, reduce throttle first if possible" rather than wait until it was 20kts over the speed bug (and in your case overspeed) to put drag required on the fmc.

Im as interested as you to know what the N1 should be during descent, I can say its almost certainly being increased due to the engines windmilling.

**Comment by abuelo007X** [comment]
I was thinking that may be the case wind impacting it, but was not sure. Thank you !!!
