### ISSUE TITLE
[AP] FLCH and VNAV SPD do not function in the way the should

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#781]
Both VNAV SPD and FLCH do no longer
pitch for speed.

If the target speed increases and the thrust remains the same
the pitch angle must be reduced 
in order to exchange climb rate for airspeed.

**FLCH and VNAV SPD
must eventually _hold the target speed_
as long as the plane climbs or descends.** 

Unfortunately this is no longer happening.

https://user-images.githubusercontent.com/78870770/163694420-48b14401-603d-4713-b8aa-81a4c4129d43.mp4

**Comment by PilotMathews** [comment]
OMG THANKYOU! This is a major issue I keep forgetting to post about. Not only does it refuse to pitch for speed on climb, but it also will adjust the throttle to speed-up or speed-down on-climb, rather than having a fixed climb thrust and pitching up or down to adjust speed...

**Comment by mSparks43** [comment]
The speed is increasing in that video, it will climb faster once it reaches the speed bug.

**Comment by oMrSmith** [comment]
With the MCP ALT set above the current ALT
FLCH will increase the VS in order to limit the airspeed to a selected value.
If the target speed is higher than the current speed,
the plane does not need to climb in order to limit the speed!
In fact it will fly level (VS = 0) until it has accellerated to that target speed.

This can be easily tested with any plane by FF for example:
disengage A/T, select ALT HOLD, stabalize the SPD,
then set higher MCP ALT and select FLCH.
increase the target MCP Speed,
then increase thrust.

The plane will fly level until it reaches the speed
from which point it will increase the VS
in order to limit the speed to the target speed.

**Comment by oMrSmith** [comment]
In fact I'm just flying version 2.0.
VNAV SPD works exactly like I described. 
It does not descend to acellerate unless I overshoot the FD.

**Comment by oMrSmith** [comment]
What makes the plane descend is not VNAV SPD
its the AP switching over to VNAV PTH too soon during CLIMB phase!

**Comment by mSparks43** [comment]
> What makes the plane descend is not VNAV SPD its the AP switching over to VNAV PTH too soon during CLIMB phase!
> 
> ![image](https://user-images.githubusercontent.com/78870770/163712283-12587bc3-6652-4dd4-8e15-06c8ce3a20c3.png)

VNAV SPD and VNAV PTH are to different speed modes.

VNAV SPD is used for climbing, thrust is max and speed is controlled by rate of climb

VNAV PTH is used for ALT hold and descent. Speed is controlled by the throttles and the descent follows the path.

specifically what I think you are referring to is this bit of code
https://github.com/mSparks43/747-400/blob/4d229a0fc4ee4b7a73232d72a84ad90dc9b3c41f/plugins/xtlua/scripts/B747.19.xt.hydraulicsmodel/B747.19.xt.hydraulics_override.lua#L425

Used when pitch mode is FLCH or VNAV SPD
atm that only requires that there is acceleration when speed is lower than the bug, and deceleration when the speed is higher than the bug.

A method I used for alt hold mode is a sliding window which would probably work better (used just below when pitch mode is not 2 (glideslope), is 5 or 9 (VNAV ALT or ALT) or its withing 1000 feet of the target altitude.
This "closes the window" as it approaches the target, e.g. climb between 1000 and 50 fpm when 1000 feet below the target, but  only 1 to 0.1 fpm when 1 foot below the target. probably wants something similar here, but would need some footage of a climb and level off profile to calibrate it to. 

> In fact I'm just flying version 2.0. 
> I believe it used to work pretty perfect.

Yeah, all that is gone, because it wasn't represented in the flight director, which the AP now uses to fly.

**Comment by mSparks43** [comment]
please retest
