### ISSUE TITLE
2.3 | Testflights [LGMK 34 VARI1C VARIX R19 KEA ILS-Z-03L LGAV]

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#813]
Hey Sparky,

these were my observations on my testflights with 2.3:

- When reaching the ACCEL HEIGHT, which is set in the FMC, 
VNAV should bug for the highest speed allowed!
That would be 240 knots, if nothing in the SID forbids this.
Currently it takes ages for VNAV to bug up the speed. 

- Thrust should changes from TO to CLB when reaching the ACCEL HEIGHT,
 which is set in the FMC and not at 1000 ft per se.

- Flap config warning triggers after landing.

- "Positive Rate" gets triggered even during approach.

- When VNAV initiates the descend after crossing the T/D, 
the A/T will set N1, if the MCP window is open, causing massive overspeed.

- (several LNAV problems...)

- Resetting MCP ALT does not clear FMC message "Reset MCP ALT".

- During climb VNAV sets speeds above 250, even while still below 10.000 ft. [Route Related]
- After reaching the ACCEL height, N1 switches to CRZ thrust instead of CLIMB thrust.
It's almost as if the plane would skip the climb-phase... [Route Related]

- Waypoints disappear when switching map to plan-view.

- Entering the RW on the RTE page does not preselect it on the DEP page.

- flickering speed bug during low CRZ, 
- Changing the mach speed on the CRZ page has no effect.

- Pitch FD too low during take off (doesn't show pitch for speed of V2 + 20)

- Very first time engaging HDG SEL (LNAV >> HDG) will disconnect CMD.

- VNAV SPD / FLCH can neither accelerate nor deccelerate to a new target speed.
Target speeds well never be reached. 

- Strong oscillation of the vertical speed when VNAV SPD 
tries to accelerate after reaching 10.000 ft due to mailfunctioning of VNAV SPD.

- VNAV SPD get's stuck on VNAV ALT when reaching CRZ ALT:

![747-400 - 2022-06-26 21 29 06](https://user-images.githubusercontent.com/78870770/175831345-ea84d7b5-bd53-47ff-b394-dbe4677cb6ea.png)

**Comment by mSparks43** [comment]
please can you attach the jdat file from the flight (in the livery folder)

**Comment by mSparks43** [comment]
> * FLCH / VNAV SPD don't really pitch for speed,
>   which becomes obvious as soon as
>   the target speed differs significantly from the current speed.

Well, it does, but its very different to XP default:
Rate of acceleration and deceleration is generally more gradual to avoid harsh pitch changes, can/should probably speed this up, but I could do with some feedback on how responsive the real one is.
When descending it will(should) never climb to slow down, when ascending it will never descend to speed up (believe the real one works like this), this puts a limit on how quickly it can slow down when descending and how quickly it can accelerate when climbing (XP has no such limits and will often break the no climb/descend rules)

**Comment by mSparks43** [comment]
> * VNAV SPD doesn't switch over to VNAV PTH after reaching CRZ ALT:

Still not tested low CRZ alts, can look at this when I get the flight recording. Probably going to want to get some more data in there, plan was to get everyone on 2.3 so I can start dissecting flight recordings for things like this.

**Comment by oMrSmith** [comment]
> this puts a limit on how quickly it can slow down when descending and how quickly it can accelerate when climbing (XP has no such limits and will often break the no climb/descend rules)

I think XP has a limit which is pretty simple. If your climbing with FLCH for example and increase the MCP SPEED by let's say 50 knots, the plane will reduce the climb rate to a vertical speed of 0 until the plane has accalerated to the new target speed, then it will continue climbing.

**Comment by mSparks43** [comment]
> I think XP has a limit which is pretty simple. Example: If your climbing with FLCH and increase the MCP SPEED by let's say 50 knots, the plane will reduce the climb rate to a vertical speed of 0 until the plane has accalerated to the new target speed, then it will continue climbing.

The reason the speed bug current increases slowly with altitude instead of snapping to the next speed limit like its supposed to, is snapping from flaps up speed to 270kts usually made the aircraft crash into the ground/mountain while trying to speed up on default XP FLCH.

> [flight_data.zip](https://github.com/mSparks43/747-400/files/8990972/flight_data.zip) So is this like a flight recorder, that you programmed? Cool...

Yup, plan for 2.3->2.4 is to use these to analyse changes to the AP and fix up any issues, easier than recording a video and better data.

Looks like the AP disconnect was possibly related to
{"time":"2022/06/26 21:22:29","CASDATA":[">AIRSPEED LOW caution"]}

shortly before, I'll see if I can get a recreate doing the same steps.

**Comment by oMrSmith** [comment]
I'd appreciate if you test the my usual low CRZ route from LGMK to LGAV.

**Comment by oMrSmith** [comment]
> Looks like the AP disconnect was possibly related to
> {"time":"2022/06/26 21:22:29","CASDATA":[">AIRSPEED LOW caution"]}

I don't think so. The HDG SEL button works almost like a AP disconnect button
the very first time I press it. I have this issue since half a year or so.
The second time I switch from LNAV to HDG all works fine...

**Comment by mSparks43** [comment]
> the very first time I press it. I have this issue since half a year or so.

I just tried about 3 or 4 take offs and couldn't get a recreate on this, even with a more or less identical jdat (just added an issue for FDR improvements), please could you get it on video so I can try and track down what/where is causing the disconnect.

**Comment by oMrSmith** [comment]
> please could you get it - and the steps leading up to it - on video so I can try and track down what/where is causing the disconnect.

I'll be a bit busy for the next to weeks, but then I'll continue testing and make a video.

**Comment by oMrSmith** [comment]
https://youtu.be/kzUF_Ebzfho

**Comment by oMrSmith** [comment]
Hey @mSparks43,

I recorded a public test-flight:
https://youtu.be/kzUF_Ebzfho?t=338

All issues I noticed are listed above
and I will keep this list updated.

**Comment by mSparks43** [comment]
> I recorded a public test-flight: https://youtu.be/kzUF_Ebzfho?t=338

> * the A/T will add thrust, if the MCP window is open, causing massive overspeed.

Watching the video - wasn't actually the A/T, thrust mode switched to hold mode and the throttle was added by your joystick (noise, causing XP to think you moved it)

**Comment by oMrSmith** [comment]
> pull your joystick back to idle just before your cross T/D

Thanks for the info, I'll try that out.

**Comment by mSparks43** [comment]
Something else, _very_ weird is happening to, at 4.28, thrust mode switches from take off to go around... I'll have a look at recreating that flight as closely as I can and see why the other stuff is happening.

**Comment by oMrSmith** [comment]
Maybe this happens because the thrust already changes to CRZ thrust after take off (instead of CLB thrust)...

**Comment by mSparks43** [comment]
> Maybe this happens because the thrust already changes to CRZ thrust after take off (instead of CLB thrust)...

```
if B747DR_ap_autoland==-2 or (B747DR_ap_flightPhase >= 2 and simDR_flap_ratio > 0 and simDR_radarAlt1<1500) then
		newTarget = "GA"```

sets GA engine mode. 

Which in English is "pressed TOGA while in the air" or "trying to descend, flaps down and less than 1500 feet RA"
Since you are on the ground, it must think you are trying to descend, that would also explain the CRZ, and quite possibly limiting pitch up.

so working theory - its pressure altitude related, any idea why the autopilot thought you are above 8000 feet sat on the runway at 400 feet?

**Comment by oMrSmith** [comment]
Maybe there's a bug when starting with "engines started"
which is what I did...

**Comment by mSparks43** [comment]
> Maybe there's a bug when starting with "engines started" which skips the flight phases?!

Or.... were you past ToD when you pressed VNAV...

**Comment by oMrSmith** [comment]
I think that strange thing happens at 
https://youtu.be/kzUF_Ebzfho?t=264
which you already mentioned.

In the moment I armed VNAV on ground,
the thrust changes from TO to GA.

**Comment by oMrSmith** [comment]
Just jumped in the plane. This time it 
went from TO to GA shortly after take off,
then after a few seconds from GA to CRZ... Very strange indeed...

**Comment by mSparks43** [comment]
So the source of most of the issues is its putting the aircraft into descent mode before you take off, just got a recreate using the same flight plan.

Looks like the cause is that flight plan crashing the AP

```
[string "scripts/B747.70.xt.autopilot/B747.70.xt.autop..."]:1929: attempt to index a nil value
stack traceback:
	[C]: in function '__index'
	[string "scripts/B747.70.xt.autopilot/B747.70.xt.autop..."]:1929: in function 'setDistances'
	[string "scripts/B747.70.xt.autopilot/B747.70.xt.autop..."]:1511: in function 'B747_fltmgmt_setILS'
	[string "scripts/B747.70.xt.autopilot/B747.70.xt.autop..."]:2904: in function 'func'
	[string "init.lua"]:489: in function <[string "init.lua"]:483>
```

**Comment by oMrSmith** [comment]
The issue must be rather new though, at least I can't remember this to happen
in earlier versions...

**Comment by oMrSmith** [comment]
Your diagnosis seems to be right.
I'm just flying a different route and thankfully the thrust mode now changes correctly from TO to CLB.

**Comment by oMrSmith** [comment]
> Watching the video - wasn't actually the A/T, thrust mode switched to hold mode and the throttle was added by your joystick (noise, causing XP to think you moved it)
> 
> pull your joystick back to idle just before your cross T/D

I just re-checked. It is not my throttle as I set it to idle before reaching T/D:

![747-400 - 2022-08-13 11 39 18](https://user-images.githubusercontent.com/78870770/184478354-c03bbe0e-f37f-4570-8215-045414c8c158.png)

After crossing the T/D, the plane switches to VNAV SPD - probably because the MCP SPD window is open -
but then the thrust goes up to N1, just as it would have to during climb.
The thrust mode "HOLD" which is printed as the FMA is not actually active.

**Comment by oMrSmith** [comment]
I think the solution to this could be fairly simple:
If the selected MCP ALT is higher VNAV SPD works as climb mode with thrust N1
if lower, VNAV SPD works as descend mode with thrust going IDLE.

**Comment by mSparks43** [comment]
> I think the solution to this could be fairly simple: If the selected MCP ALT is higher VNAV SPD works as climb mode with thrust N1 if lower, VNAV SPD works as descend mode with thrust going IDLE.

yep, so did I -> exactly this is pretty much what is breaking here....

there are quite a few issues seemingly coming together. 

First, it's failing to calculate an EoD for this flight plan
This works fine on the one I normally test on as soon as I load the flightplan
![image](https://user-images.githubusercontent.com/6773686/184518024-408cee0d-8f95-4e02-af1b-511b1baacff7.png)

On this plan it doesn't - technically its supposed to 
![image](https://user-images.githubusercontent.com/6773686/184518035-b11fd069-70cd-4ac8-a362-ac3f6b5d55d5.png)

with an (as yet unimplimented)
![image](https://user-images.githubusercontent.com/6773686/184518058-56bf7946-9abe-444a-b7bf-5f2e547e8501.png)
to fix it.

That's also the "nil index" in the stack trace I posted above

Secondly, while I can't get it to happen on the ground, it is switching into descent/cruise mode prematurely, which is what breaks all the climb stuff

Thirdly, I've no idea why its failing to calculate an EoD yet, it should. I'll have to look at what flight plan data xplane sending the FMC.

First thing I'll do (after posting this) is track down why its leaving climb mode early.

Then, since no EoD is so catastrophic to the rest of the calculations, next thing I'll do is fire "PERF/VNAV UNAVAILABLE" when there is no EoD calculated, that's actually not included as a condition in the older fcom pinned in the discord

![image](https://user-images.githubusercontent.com/6773686/184518252-11f9827d-40e5-496e-9a75-151eb4bdbda8.png)

which is why the check isn't there already.

Once those are in, track down why it fails to find an EoD, and add RWY EXT to fix it, that's a good one for better VNAV approaches anyway.

**Comment by oMrSmith** [comment]
Thanks for your investigations! I know it's still a lot of work... 
Just for your info: The A/T issue happened on another route too.
I picked a longer one to make life easier for the plane...
In fact most of the issues listed above, appeared on the longer route (LEIB-LEMH) too.
Do you want me to issue them seperately?
Some of them already are...

**Comment by oMrSmith** [comment]
And: Shell I continue to test your fixes with the forbidden route (LGMK-LGAV)
or take a longer one? ;)

**Comment by mSparks43** [comment]
> And: Shell I continue to test your fixes with the forbidden route (LGMK-LGAV) or take a longer one? ;)

Yes, was testing on that.

->the A/T will add thrust, if the MCP window is open, causing massive overspeed.

I think this is having the speed window open switching it to hold, in hold you have to manually control the thrust - but also VNAV speed was still very lethargic in descent, there's a fix in for that.

**Comment by oMrSmith** [comment]
> I think this is having the speed window open switching it to hold, in hold you have to manually control the thrust (so rather than noise, it was a lack of movement)

The problem is that HOLD was shown a s the FMA but not actually working.
In my latest test, the my hardware throttle was idle and the A/T increased thrust to N1
eventhough the FMA said HOLD.

**Comment by mSparks43** [comment]
> In my latest test, my hardware throttle was set to idle and the A/T increased thrust to N1
> even though the FMA said HOLD.

because the speed window is open descent goes to HOLD thrust and VNAV SPD pitch - this is "as it should be", HOLD will send the throttle back to the last joystick throttle XP has (probably from take off), you actually need to move physically move it to get a change to register.

The overspeed wasn't caused by the higher than normal thrust - it was caused by VNAV SPD pitching down to much, accelerating, and not pitching up to slow it down.

**Comment by oMrSmith** [comment]
> The overspeed wasn't caused by the higher than normal thrust

You can literally read on the display that thrust increases to N1!

**Comment by oMrSmith** [comment]
I only have the SPD Window open 
to avoid the flickering SPD bug during CZR...

**Comment by mSparks43** [comment]
> You can literally read on the display that thrust increases to N1!

Yes - but speed isn't being controlled by the thrust, its gone to VNAV SPD (rather than VNAV PTH) because the speed window is now open in descent - the speed is _supposed_ to be controlled by the pitch.

![image](https://user-images.githubusercontent.com/6773686/184551497-68ff69e0-1a9d-40a5-8720-95f23f38b15e.png)


To reduce the thrust in this situation the throttle needs moving to idle, physically, after thrust mode moves to hold (xplane ignores moving it to idle while thrust mode is SPD)
