### ISSUE TITLE
2.3 | Climbing is impossible, VNAV & V/S both fail to climb properly & rocket past the set rate.

### ISSUE THREAD

**Issue by basedwarcriminal** [mSparks43/747-400#814]
Hi Sparky.

After updating to V2.3 today, I took the 747 on a flight from PHNL - YSSY. Just after departure from Honolulu, the aircraft's climb rate with VNAV was absurdly high, and VNAV wasn't maintaining any formality. It would zoom up to 7000fpm, then after I pitched the aircraft down manually, continue descending slowly to regain lost speed. I switched to V/S, which changed nothing. I set +2000, watched the aircraft climb to maintain a vertical speed of 2000, and just as it was holding it for a few seconds, it started skyrocketing again. The autopilot's only functioning feature is LNAV and THR from what I've seen. I closed the sim shortly after passing 14000ft if I remember correctly because that was incredibly difficult to manage and nothing I tried would fix it. I've attached the .jdat and some rushed images, so apologies if the images don't show much. Thanks.

[flightdata.zip](https://github.com/mSparks43/747-400/files/8991896/flightdata.zip) (location of the .jdat)
![747-400 - 2022-06-27 22 08 42](https://user-images.githubusercontent.com/104433718/175940702-ccea8bbe-7121-4ac3-8a29-cd8a301c4bff.png)

![747-400 - 2022-06-27 22 08 39](https://user-images.githubusercontent.com/104433718/175940684-f18db1f0-f5ca-4ea0-86a3-c759696694e5.png)

(Do keep in mind that these images only show a small phase of what happened, I was busy attempting to sort the issue, apologies once again)

**Comment by mSparks43** [comment]
> (Do keep in mind that these images only show a small phase of what happened, I was busy attempting to sort the issue, apologies once again)

The livery folder of the aircraft will have a jdat file in it - its the flight recording, please attach :p

**Comment by basedwarcriminal** [comment]
Alright, makes perfect sense. I did notice in the FMC that there was quite a lot of blank data in the airline section, and the simconfig didn't have the engines selected so I had to go through and grab them. I'm hoping it's just a livery problem and not a full aircraft problem. When I have time I'll try another flight, and if I see any issues, I'll be sure to post! Thanks again.

**Comment by prokopiu** [comment]
I also did a test flight last weekend (the Boeing default livery) which you can follow on this unlisted video on YT:

https://youtu.be/BzQ0CUDZhak

00:50:03 I activate the autopilot, the plane is climbing with >5000 ft/min (probably because it is light) but then it exceeds the commanded speed – pulling the thrust lever axis to idle (in case of joystick interference) seem to have helped, the plane started to move the speed towards the commanded value (although not precisely).

00:51:41 The plane started to descend uncommanded and accelerate. I switched from VNAV to FLCH and then to VS mode to fix the descend rate. When VS mode was turned on, the plane stabilized. Turned VNAV on again then everything normalized – may have been linked to thrust axis interfering?? 

The rest of the flight went fine apart from a minor glitch during AUTOLAND approach.

**Comment by bluemesa5280** [comment]
I also have experienced VNAV not working properly while using the included United livery. Have not tried other liveries. May indeed be related to PW4056 engines.

 flight_data.jdat file is attached
[flight_data.zip](https://github.com/mSparks43/747-400/files/9050630/flight_data.zip)
.

**Comment by mSparks43** [comment]
please retest
