### ISSUE TITLE
[AP] FLCH (and VNAV SPD) can't properly accelerate to a new Target Speed during Climb due to Oscillation of VS

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#830]
Oscillation in the vertical speed 
and slow pitch adjustment
hinder both FLCH and VNAV SPD to
accelerate to a new target speed:

https://youtu.be/K0zQFMAugrw

**Comment by oMrSmith** [comment]
Hey @mSparks43 , could you please have a look at the video?

**Comment by oMrSmith** [comment]
So, acceleration to a new target speed can now be achieved in time.
However, this has made one problem, which I think you were trying to avoid, worse:
The plane descends in order to accelerate. VS goes down to negative values.

![747-400 - 2022-08-16 13 46 26](https://user-images.githubusercontent.com/78870770/184872803-a959f6c5-a29e-481e-bd1b-71a3e2162e06.png)

So having the pitch angle being adjusted quicker is good.
But the VS must not drop below 0 fpm.

**Comment by mSparks43** [comment]
This should be fixed now, increased the minimum descend rate during climb when it can pitch the nose down more (and vice versa) to 200fpm

**Comment by oMrSmith** [comment]
Is just tested. I think you have significantly improved FLCH! Still as you increase the target speed
it dips down below fpm initially during climb. However after that acceleration seems quite stable
and the  oscillation from before seems gone!

**Comment by oMrSmith** [comment]
Just tested. I think you have significantly improved FLCH! Still, as you increase the target speed during climb,
the plane briefly dips down below 0 fpm initially. However after that the acceleration works quite stable
and the  oscillation from before seems to be gone!

**Comment by oMrSmith** [comment]
FLCH has really been my bigges concern with the plane... glad you improved this.

**Comment by mSparks43** [comment]
> Just tested. I think you have significantly improved FLCH! Still, as you increase the target speed during climb, the plane briefly dips down below 0 fpm initially. However after that the acceleration works quite stable and the oscillation from before seems to be gone!

could perhaps try increasing it to 500 its set by the 200 here
https://github.com/mSparks43/747-400/blob/db3443aeeb57e6b698b8c5cc8e5cb9816404a12a/plugins/xtlua/scripts/B747.19.xt.hydraulicsmodel/B747.19.xt.hydraulics_override.lua#L455

didn't want to go much higher than 200 in case its near maximum altitude.
If that isn't enough I can put a cap on the maximum rate of acceleration demanded when its away from the speed bug.

**Comment by oMrSmith** [comment]
I think FLCH is basically going in the right direction! It could need some fine tuning but for now its good I think.
What I noticed is that as you reach the new target speed (during climb), it is like to be overshot as the plane takes a bit too long 
to increase pitch again after acceleration has been achieved...

**Comment by CalibraNR** [comment]
Hello all, using latest files from GitHub (mirrored), do not know if it can be of any use, but after Take Off, even selecting V/S instead of FLCH the aircraft still nose dives to get speed than starts climbing. As far as I am concerned it would not behave like that, it should prioritize the Vertical Speed selection, even draining speed if it's the case.

That behavior manifests not only on T/O, I could also verify it when using VS, AFCS prioritizes the airspeed. Let's take the descent for example, If you are faster than the airspeed selected it first reduces the descent rate in order to reduce speed than start descending on the V/S Selected. As far as I know that's not the way VS Mode should works.

There's any way I can help to better provide any insightful information on this matter?

Thanks

As always, thank you very much for your effort.

**Comment by mSparks43** [comment]
@CalibraNR please could you post a video to make it easier to recreate exactly what you are referring to (I get the jist, but not 100% sure how to make it behave as you describe)

**Comment by mSparks43** [comment]
please retest
