### ISSUE TITLE
 L NAV Y NAN the commands do not enter

### ISSUE THREAD

**Issue by Morfeo73** [mSparks43/747-400#842]
# Feaure Request

Sparky744 XP1205_2023_04_24 
### Describe the feature
Sparky744 XP1205_2023_04_24 x-plane version 11 the LNAV and YNAV commands are not inserted with autopilot inserted. The AUTOTHROT command is disconnected. I tried 2 times to install the version by also downloading the Sparky744.XP11.backport.zip file.
I first downloaded and installed the 744.XP1205_2023_04_09.zip files
and 747-400.XP1205-2023_04_24.0617.zip finally I overwrote the Sparky744.XP11.backport.zip file.

The problem persists, I'm wrong in the installation or I forget some steps.
I downloaded the latest version because always using the 747 Sparky previous versions, often the runways with ILS approach did not respond to the APP command
Thanks, I look forward to clarification 

### Visual Reference
If applicable, add screenshots or videos to help explain your request. Please upload or send a link below:

**Comment by mSparks43** [comment]
This doesn't sound like an installation issue.

by 
> LNAV not inserted, 

I presume you mean LNAV wont arm/activate. That would geberally be caused by not pressing exec after entering/making changes to a flight plan.

please check in the latest version (that does have ILS fixes in), and if the problem persists grab a video for diagnosis.

additionally, each time you fly the aircraft, lots of data about the flight gets saved in the livery folder in a file called flight_data.jdat. that file can be very useful in diagnosing why things happened.
