### ISSUE TITLE
ND/FMC ETA disagreement

### ISSUE THREAD

**Issue by Koploper9** [mSparks43/747-400#91]
On version 2020/11/21 17:17 I noticed that the ETA in the ND and the FMC don't match:

![ETA](https://user-images.githubusercontent.com/21144174/99905640-5a9e2500-2cd2-11eb-869b-d80735889643.png)

I checked it and the one on the ND was correct. I did some calculations and the ND calculates the ETA from the current groundspeed, while the FMC calculates based on the planned VNAV speed of M081. At that moment I had set a manual speed in the MCP, but VNAV was still enebled.

Possible solution: Use speed setting from speed bug to calculate ETA.

**Comment by mSparks43** [comment]
This was the default XP FMS calculating things wrong. fixed with matching the PROG page to the real one
![image](https://user-images.githubusercontent.com/6773686/148657672-1425c737-b9a4-4e3c-853f-b590fc5c83a5.png)
![image](https://user-images.githubusercontent.com/6773686/148657678-f88371e3-1365-4ad7-a3dc-357c73e49fa9.png)
![image](https://user-images.githubusercontent.com/6773686/148657683-7f293a74-717e-451b-965b-9d07e71abed2.png)
